language: android
jdk: oraclejdk8
dist: precise
android:
  components:
    - tools
    - platform tools
    - tools
    - android-26
    - build-tools-26
    - extra
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
      - 'android-sdk-license-c81a61d9'



before_install:
  - echo yes | android update sdk --all --filter build-tools-26 --no-ui --force
  - chmod +x gradlew

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - ./gradlew clean